[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate=lib/solmate/src/',
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@foundry-devops/=lib/foundry-devops/"]

fs_permissions = [{ access = "read", path = "./broadcast" }] # Allow foundry to run commands on the command line

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config